config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'pages#index'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  match 'logout' => 'sessions#destroy', via: [:all]

  namespace :admin do
    resources :users
    resources :roles
  end

  root 'sessions#new'

end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :roles, dependent: :destroy

	validates :email, uniqueness: true
	accepts_nested_attributes_for :roles
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:user_id, :title, :status, :salary, :salary_terms)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @role = @user.roles.build
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, roles_attributes: [:title, :status, :salary, :salary_terms])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login
  include SessionsHelper

  private
  	def require_login
  		unless logged_in?
  			redirect_to login_path, flash: { message: "You need to login to access the page." }
  		end
  	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def user_session(user)
  	session[:user_id] = user.id
  end

  def new
    if logged_in?
      redirect_to home_path
    end
  end

  def create
  	@user = User.find_by(email: params[:email])

  	if @user && @user.authenticate(params[:password])
  		user_session(@user)  		
  	end

    redirect_to home_path
  end

  def destroy
  	reset_session

  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
	def title_options
		[['Admin', 'admin'], ['Manager', 'manager'], ['Bookkeeper', 'bookkeeper'], ['Cashier', 'cashier'], ['Waiter', 'waiter'], ['Cook', 'cook']]
	end

	def role_status_options
		[['Trainee', 'trainee'], ['Part-time', 'part-time'], ['Probation', 'probation'], ['Regular', 'regular']]
	end

	def salary_term_options
		[['', nil], ['Daily', 'daily'], ['Monthly', 'monthly']]
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def logged_in?
		!session[:user_id].blank? ? true : false
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/roles/_form.html.haml
= form_for @role do |f|
  - if @role.errors.any?
    #error_explanation
      %h2= "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"
      %ul
        - @role.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :salary
    = f.text_field :salary
  .field
    = f.label :salary_terms
    = f.text_field :salary_terms
  .actions
    = f.submit 'Save'

app/views/admin/roles/edit.html.haml
%h1 Editing role

= render 'form'

= link_to 'Show', @role
\|
= link_to 'Back', roles_path

app/views/admin/roles/index.html.haml
%h1 Listing roles

%table
  %thead
    %tr
      %th User
      %th Title
      %th Status
      %th Salary
      %th Salary terms
      %th
      %th
      %th

  %tbody
    - @roles.each do |role|
      %tr
        %td= role.user
        %td= role.title
        %td= role.status
        %td= role.salary
        %td= role.salary_terms
        %td= link_to 'Show', role
        %td= link_to 'Edit', edit_role_path(role)
        %td= link_to 'Destroy', role, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Role', new_admin_role_path

app/views/admin/roles/new.html.haml
%h1 New role

= render 'form'

= link_to 'Back', roles_path

app/views/admin/roles/show.html.haml
%p#notice= notice

%p
  %b User:
  = @role.user
%p
  %b Title:
  = @role.title
%p
  %b Status:
  = @role.status
%p
  %b Salary:
  = @role.salary
%p
  %b Salary terms:
  = @role.salary_terms

= link_to 'Edit', edit_role_path(@role)
\|
= link_to 'Back', roles_path

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  = f.fields_for :roles do |r|
    .field
      = r.label :title
      = r.select :title, options_for_select(title_options)
    .field
      = r.label :status
      = r.select :status, options_for_select(role_status_options)
    .field
      = r.label :salary
      = r.number_field :salary
    .field
      = r.label :salary_terms
      = r.select :salary_terms, options_for_select(salary_term_options)
  .field
    = f.label :email
    = f.email_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/admin/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', admin_user_path
\|
= link_to 'Back', admin_users_path

app/views/admin/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Email
      %th Password digest
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.password_digest
        %td= link_to 'Show', admin_user_path(user)
        %td= link_to 'Edit', edit_admin_user_path(user)
        %td= link_to 'Destroy', admin_user_path(user), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_admin_user_path

app/views/admin/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', admin_users_path

app/views/admin/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Password digest:
  = @user.password_digest
%p
  %b Roles
  - if @user.roles.blank?
    No Role.
  - else
    %ul
      - @user.roles.each do |r|
        %li
          = r.title.titleize
          = r.salary
          = r.salary_terms

= link_to 'Edit', edit_admin_user_path(@user)
\|
= link_to 'Back', admin_users_path

app/views/layouts/_admin_menu.html.haml
%div
  %a{ href: home_path } Home
  - if logged_in?
    %a{ href: logout_path } Logout

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bizzpod
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/admin_menu'
    = yield

app/views/pages/index.html.haml
%h1 Home

%a{ href: admin_users_path }
  Users

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Password digest:
  = @user.password_digest

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path